export const TEST = "TEST";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_INVALID = "LOGIN_INVALID";


export const GET_POSTS = "GET_POSTS";


export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_INVALID = "REGISTER_INVALID";

export const SEARCH_SUCCESS = "SEARCH_SUCCESS"

export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const ALL_MOVIES_LOAD_MORE = "ALL_MOVIES_LOAD_MORE"
export const ALL_MOVIES_LOAD_MORE_SUCCESS = "ALL_MOVIES_LOAD_MORE_SUCCESS"






export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_BLOG_POSTS = "GET_BLOG_POSTS";






export const LOADER = "LOADER";
